name: API Tests

on:
  push:
    branches: 
      - main
      - develop
  pull_request:
    branches: [ main ]

jobs:
  test:
    runs-on: ubuntu-latest

    env:
      TESTRAIL_URL: ${{ secrets.TESTRAIL_URL }}
      TESTRAIL_EMAIL: ${{ secrets.TESTRAIL_EMAIL }}
      TESTRAIL_API_KEY: ${{ secrets.TESTRAIL_API_KEY }}
      TESTRAIL_RUN_ID: ${{ secrets.TESTRAIL_RUN_ID }}

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'
      
      - name: Check contents of workspace
        run: |
          ls -lah

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Clean Google Chrome user data dir (prevent user-data-dir error)
        run: |
          rm -rf ~/.config/google-chrome || true

      - name: Check Python & pip packages
        run: |
          which python
          which pip
          pip list
      
      - name: Check test files
        run: |
          ls -R

      - name: Set PYTHONPATHPYTHONPATH=$(pwd) pytest tests
        run: echo "PYTHONPATH=$(pwd)" >> $GITHUB_ENV
      
      # if running normal tests
      - name: Run Selenium tests
        run: |
          pytest tests --maxfail=2 --disable-warnings -v --html=reports/report.html

      # if running parallel tests
     # - name: Run test in parallel
      #  run: |
       #   pytest -n auto --disable-warnings -v \
        #    --html=reports/report.html \
         #   --self-contained-html \
          #  --alluredir=reports/allure-results \
           # --maxfail=2

      - name: Generate Allure HTML Report 
        run: |
          npm install -g allure-commandline --save-dev
          allure generate reports/allure-results -o reports/allure-report --clean

      - name: Upload Allure HTML Report
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: allure-html
          path: reports/allure-report

      - name: Upload HTML report
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: selenium-report
          path: reports/report.html

      - name: Upload Allure Report Artifact
        uses: actions/upload-artifact@v4
        with:
          name: allure-results
          path: reports/allure-results/
